### ISSUE TITLE
Google smart chip Phase 2 - ETL Google smart chip sheet

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-google-workspace-smart-chip#6]
ETL Google smart chip sheet into Artsdata
```[tasklist]
### Tasks
- [x] Create Artsdata Stewards organization in Github
- [x] Create workflow using params
- [x] Action on artifact to run workflow with params
- [x] Generate publisher id from user's Github handle
- [x] Form to create a new artifact
- [x] Validate permission to contribute new source using Github teams (databus account) in Artsdata Stewards
```

**Comment by saumier** [comment]
@saumier Need to check the account from the github login.
